"""add interview weight

Revision ID: 2acc9098d543
Revises: bce4d7df4bbb
Create Date: 2026-08-25 22:54:16.065330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2acc9098d543'
down_revision: Union[str, Sequence[str], None] = 'bce4d7df4bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('interview_weight', sa.Integer(), server_default='50', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'interview_weight')
    # ### end Alembic commands ###
