"""add resume project summary

Revision ID: 2ea61b36e0bb
Revises: 8cea08a3268f
Create Date: 2026-09-02 22:05:15.618978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea61b36e0bb'
down_revision: Union[str, Sequence[str], None] = '8cea08a3268f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('project_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'project_summary')
    # ### end Alembic commands ###
