"""add application withdrawal

Revision ID: 3515239df83f
Revises: 54ddbd716e07
Create Date: 2026-09-09 04:29:45.514982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3515239df83f'
down_revision: Union[str, Sequence[str], None] = '54ddbd716e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE applicationstatus ADD VALUE 'WITHDRAWN'")
    op.add_column('applications', sa.Column('hidden_by_candidate', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'hidden_by_candidate')
    # ### end Alembic commands ###
