"""add assessment time limit

Revision ID: 54ddbd716e07
Revises: e03d4fff0b2b
Create Date: 2026-09-08 03:47:16.908234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ddbd716e07'
down_revision: Union[str, Sequence[str], None] = 'e03d4fff0b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('assessment_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('assessment_time_limit_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'assessment_time_limit_minutes')
    op.drop_column('applications', 'assessment_started_at')
    # ### end Alembic commands ###
