"""restructure skill taxonomy tables

Revision ID: 6487456be9e3
Revises: bb87e9e80517
Create Date: 2026-08-28 04:29:08.105560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6487456be9e3'
down_revision: Union[str, Sequence[str], None] = 'bb87e9e80517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_groups_id'), 'skill_groups', ['id'], unique=False)
    op.create_index(op.f('ix_skill_groups_key'), 'skill_groups', ['key'], unique=True)
    op.create_table('unknown_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('normalized_text', sa.String(), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unknown_skills_id'), 'unknown_skills', ['id'], unique=False)
    op.create_index(op.f('ix_unknown_skills_normalized_text'), 'unknown_skills', ['normalized_text'], unique=False)
    op.create_table('skill_group_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['skill_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'language')
    )
    op.create_index(op.f('ix_skill_group_labels_id'), 'skill_group_labels', ['id'], unique=False)
    op.create_index(op.f('ix_skill_group_labels_language'), 'skill_group_labels', ['language'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['skill_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('skill_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_aliases_alias'), 'skill_aliases', ['alias'], unique=True)
    op.create_index(op.f('ix_skill_aliases_id'), 'skill_aliases', ['id'], unique=False)
    op.drop_index(op.f('ix_interview_answers_id'), table_name='assessment_answers')
    op.create_index(op.f('ix_assessment_answers_id'), 'assessment_answers', ['id'], unique=False)
    op.drop_index(op.f('ix_interview_questions_id'), table_name='assessment_questions')
    op.create_index(op.f('ix_assessment_questions_id'), 'assessment_questions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_questions_id'), table_name='assessment_questions')
    op.create_index(op.f('ix_interview_questions_id'), 'assessment_questions', ['id'], unique=False)
    op.drop_index(op.f('ix_assessment_answers_id'), table_name='assessment_answers')
    op.create_index(op.f('ix_interview_answers_id'), 'assessment_answers', ['id'], unique=False)
    op.drop_index(op.f('ix_skill_aliases_id'), table_name='skill_aliases')
    op.drop_index(op.f('ix_skill_aliases_alias'), table_name='skill_aliases')
    op.drop_table('skill_aliases')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_skill_group_labels_language'), table_name='skill_group_labels')
    op.drop_index(op.f('ix_skill_group_labels_id'), table_name='skill_group_labels')
    op.drop_table('skill_group_labels')
    op.drop_index(op.f('ix_unknown_skills_normalized_text'), table_name='unknown_skills')
    op.drop_index(op.f('ix_unknown_skills_id'), table_name='unknown_skills')
    op.drop_table('unknown_skills')
    op.drop_index(op.f('ix_skill_groups_key'), table_name='skill_groups')
    op.drop_index(op.f('ix_skill_groups_id'), table_name='skill_groups')
    op.drop_table('skill_groups')
    # ### end Alembic commands ###
