"""add job closed flag and creation date

Revision ID: 88be3acf8b8c
Revises: 2acc9098d543
Create Date: 2026-08-26 00:12:00.256336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88be3acf8b8c'
down_revision: Union[str, Sequence[str], None] = '2acc9098d543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_closed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'is_closed')
    # ### end Alembic commands ###
