"""add job description raw

Revision ID: 8cea08a3268f
Revises: 1e19a45f0192
Create Date: 2026-09-02 21:51:01.227208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cea08a3268f'
down_revision: Union[str, Sequence[str], None] = '1e19a45f0192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('description_raw', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'description_raw')
    # ### end Alembic commands ###
