"""add job archive flag

Revision ID: bce4d7df4bbb
Revises: 7a8f451f7158
Create Date: 2026-08-21 22:52:57.513489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce4d7df4bbb'
down_revision: Union[str, Sequence[str], None] = '7a8f451f7158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_active')
    # ### end Alembic commands ###
