"""add accepted application status

Revision ID: e03d4fff0b2b
Revises: 2ea61b36e0bb
Create Date: 2026-09-08 02:44:12.311155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03d4fff0b2b'
down_revision: Union[str, Sequence[str], None] = '2ea61b36e0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE applicationstatus ADD VALUE 'ACCEPTED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
