EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
EMPLOYER_ROLE_REQUIRED = "EMPLOYER_ROLE_REQUIRED"
CANDIDATE_ROLE_REQUIRED = "CANDIDATE_ROLE_REQUIRED"

SKILL_NOT_FOUND = "SKILL_NOT_FOUND"

JOB_NOT_FOUND = "JOB_NOT_FOUND"
JOB_ACCESS_DENIED = "JOB_ACCESS_DENIED"
JOB_HAS_ACTIVITY = "JOB_HAS_ACTIVITY"

RESUME_NOT_FOUND = "RESUME_NOT_FOUND"
RESUME_ALREADY_EXISTS = "RESUME_ALREADY_EXISTS"
RESUME_REQUIRED = "RESUME_REQUIRED"

APPLICATION_NOT_FOUND = "APPLICATION_NOT_FOUND"
ALREADY_APPLIED = "ALREADY_APPLIED"
MISSING_MANDATORY_SKILLS = "MISSING_MANDATORY_SKILLS"

ASSESSMENT_NOT_ELIGIBLE = "ASSESSMENT_NOT_ELIGIBLE"
ASSESSMENT_ALREADY_STARTED = "ASSESSMENT_ALREADY_STARTED"
NO_QUESTIONS_SELECTED = "NO_QUESTIONS_SELECTED"
QUESTION_NOT_FOUND = "QUESTION_NOT_FOUND"
ALREADY_ANSWERED = "ALREADY_ANSWERED"

LLM_UNAVAILABLE = "LLM_UNAVAILABLE"