EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
EMPLOYER_ROLE_REQUIRED = "EMPLOYER_ROLE_REQUIRED"
CANDIDATE_ROLE_REQUIRED = "CANDIDATE_ROLE_REQUIRED"

JOB_NOT_FOUND = "JOB_NOT_FOUND"
JOB_ACCESS_DENIED = "JOB_ACCESS_DENIED"

RESUME_NOT_FOUND = "RESUME_NOT_FOUND"
RESUME_ALREADY_EXISTS = "RESUME_ALREADY_EXISTS"
RESUME_REQUIRED = "RESUME_REQUIRED"

ALREADY_APPLIED = "ALREADY_APPLIED"
MISSING_MANDATORY_SKILLS = "MISSING_MANDATORY_SKILLS"